"""crear tabla limone

Revision ID: ae4e3b224752
Revises: 
Create Date: 2026-09-28 00:25:36.799398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision: str = 'ae4e3b224752'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limone',
    sa.Column('name', String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('CLASSIC', 'TROPICAL', 'EXOTIC', 'BERRY', name='lemonadecategories'), nullable=False),
    sa.Column('flavor', String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('limone')
    # ### end Alembic commands ###
